[env:esp32s3]
platform = espressif32@^6.8.1
board = esp32-s3-devkitc-1
framework = espidf

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; ─── Waveshare ESP32‑S3 AI Smart Speaker Board ───────────────────────────────
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram = enabled
board_build.psram_size = 8MB
board_build.flash_mode = dio

; ─── Partizioni personalizzate ───────────────────────────────────────────────
board_build.partitions = partitions.csv

monitor_speed = 115200

; Impacchetta e flasha il modello wake word sulla partizione 'model'
extra_scripts = scripts/pack_srmodels.py

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT=1
    -DWAVESHARE_AUDIO_BOARD

; ─── SDKCONFIG extra ─────────────────────────────────────────────────────────
custom_sdkconfig_options =
    CONFIG_MODEL_IN_FLASH=y
    CONFIG_SR_WN_WN9_HEYKIRA_TTS3=y
